added billy

diff --git a/.github/workflows/aquasec-push.yml b/.github/workflows/aquasec-push.yml
--- a/.github/workflows/aquasec-push.yml
+++ b/.github/workflows/aquasec-push.yml
@@ -31,3 +31,24 @@ jobs:
         AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
         TRIVY_RUN_AS_PLUGIN: 'aqua'
         GITHUB_TOKEN: ${{ github.token }}
+    - name: Manifest Generation
+        run: |
+          export BILLY_SERVER=https://billy.codesec.aquasec.com
+          curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
+          curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
+          if ! cat install.sh.checksum | sha256sum --check; then
+          echo "install.sh checksum failed"
+          exit 1
+          fi
+          BINDIR="." sh install.sh
+          rm install.sh install.sh.checksum
+          ./billy generate \
+            --access-token "${{ secrets.GITHUB_TOKEN }}" \
+            --aqua-key "${{ secrets.AQUA_KEY }}" \
+            --aqua-secret "${{ secrets.AQUA_SECRET }}" \
+            --artifact-path . 
+        env:
+          AQUA_KEY: ${{ secrets.AQUA_KEY }}
+          AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
+          TRIVY_RUN_AS_PLUGIN: 'aqua'
+          GITHUB_TOKEN: ${{ github.token }}
